- tobe_blog_service/src/main/resources/schema/table.sql
> feature: init user module table

- .idea/prettier.xml
- .idea/uiDesigner.xml
- tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/ProjectDTO.java
- tobe_blog_web/public/locales/en/translation.json
- tobe_blog_web/public/locales/zh/translation.json
- tobe_blog_web/src/admin/AdminRoutes.tsx
- tobe_blog_web/src/admin/URL.ts
- tobe_blog_web/src/admin/components/header/BackendHeader.tsx
- tobe_blog_web/src/admin/components/navigator/SideNav.tsx
- tobe_blog_web/src/admin/containers/content/plan/PlanCreationPage.tsx
- tobe_blog_web/src/admin/containers/content/plan/PlanDetailPage.tsx
- tobe_blog_web/src/admin/containers/content/plan/PlansPage.tsx
- tobe_blog_web/src/i18n.ts
- tobe_blog_web/src/main.tsx
- tobe_blog_web/src/routes/URL.ts
- tobe_blog_web/src/services/PlanService.ts
- tobe_blog_web/src/services/ProjectService.ts
- tobe_blog_web/src/services/index.ts
> feat(plans): update the plans

- tobe_blog_service/src/main/java/com/tobe/blog/beans/consts/Const.java
- tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/CollectionCreationDTO.java
- tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/CollectionDTO.java
- tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/CollectionUpdateDTO.java
- tobe_blog_service/src/main/java/com/tobe/blog/beans/entity/content/CollectionEntity.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/controller/impl/CollectionController.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/mapper/CollectionMapper.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/service/impl/CollectionService.java
- tobe_blog_service/src/main/resources/com/tobe/blog/content/mapper/CollectionMapper.xml
- tobe_blog_service/src/test/java/com/tobe/blog/content/service/impl/ArticleServiceTests.java
- tobe_blog_service/src/test/java/com/tobe/blog/content/service/impl/CollectionServiceTests.java
- tobe_blog_service/src/test/java/com/tobe/blog/content/service/impl/PlanProgressServiceTests.java
- tobe_blog_service/src/test/java/com/tobe/blog/content/service/impl/PlanServiceTests.java
- tobe_blog_service/src/test/java/com/tobe/blog/content/service/impl/VOCServiceTests.java
- tobe_blog_service/src/test/resources/schema/table.sql
- tobe_blog_web/src/admin/AdminRoutes.tsx
- tobe_blog_web/src/admin/URL.ts
- tobe_blog_web/src/admin/components/navigator/SideNav.tsx
- tobe_blog_web/src/admin/containers/collection/CollectionCardView.tsx
- tobe_blog_web/src/admin/containers/collection/CollectionCreationPage.tsx
- tobe_blog_web/src/admin/containers/collection/CollectionDetailPage.tsx
- tobe_blog_web/src/admin/containers/collection/CollectionsPage.tsx
- tobe_blog_web/src/admin/containers/collection/SingleTagSelecter.tsx
- tobe_blog_web/src/global/types.ts
- tobe_blog_web/src/services/CollectionService.ts
- tobe_blog_web/src/services/index.ts
Add API and pages for managing user content collection
> Feat: Add collection module

- tobe_blog_service/src/main/java/com/tobe/blog/beans/consts/Const.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/job/ViewCountSinkingJob.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/mapper/ContentGeneralInfoMapper.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/service/impl/BaseContentService.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/service/impl/ContentGeneralInfoService.java
- tobe_blog_service/src/main/java/com/tobe/blog/portal/controller/PublicApiController.java
- tobe_blog_service/src/main/resources/com/tobe/blog/content/mapper/ContentGeneralInfoMapper.xml
- tobe_blog_web/src/admin/containers/content/article/components/ArticleEditMainSection.tsx
> Sink view count into DB minutely

- tobe_blog_web/src/commons/index.ts
- tobe_blog_web/src/components/common/TagDisplayBar.tsx
- tobe_blog_web/src/components/index.ts
- tobe_blog_web/src/global/enums.ts
- tobe_blog_web/src/global/types.ts
- tobe_blog_web/src/portal/PortalRoutes.tsx
- tobe_blog_web/src/portal/URL.ts
- tobe_blog_web/src/portal/components/AuthorDisplayPanel.tsx
- tobe_blog_web/src/portal/components/Breadcrumbs.tsx
- tobe_blog_web/src/portal/components/ContentPageBreadcrumbsBar.tsx
- tobe_blog_web/src/portal/components/ContentPageFrame.tsx
- tobe_blog_web/src/portal/components/ContentPageMetaBar.tsx
- tobe_blog_web/src/portal/components/RelevantContentPanel.tsx
- tobe_blog_web/src/portal/components/RichContentReader.tsx
- tobe_blog_web/src/portal/components/index.ts
- tobe_blog_web/src/portal/containers/domain/article/ArticleReadingPage.tsx
- tobe_blog_web/src/routes/MainRouter.tsx
> feat(article): update the articles

- tobe_blog_web/src/components/common/StrokeText.tsx
- tobe_blog_web/src/portal/components/HeaderUserMenu.tsx
- tobe_blog_web/src/portal/components/PortalHeader.tsx
- tobe_blog_web/src/portal/containers/domain/article/ArticleReadingPage.tsx
https://github.com/TOBE-TOGETHER/tobe-blog/assets/39786600/88f14b88-bf05-47b1-8253-9b2d90d7c3a2
> feat(icon): create a stroke animation component

- tobe_blog_web/src/components/common/StrokeText.tsx
- tobe_blog_web/src/portal/PortalRoutes.tsx
- tobe_blog_web/src/portal/components/Breadcrumbs.tsx
- tobe_blog_web/src/portal/components/ContentBanner.tsx
- tobe_blog_web/src/portal/components/HeaderUserMenu.tsx
- tobe_blog_web/src/portal/components/PortalHeader.tsx
- tobe_blog_web/src/portal/components/RichContentReader.tsx
- tobe_blog_web/src/portal/components/index.ts
- tobe_blog_web/src/portal/containers/content/article/ArticleReadingPage.tsx
- tobe_blog_web/src/portal/containers/domain/article/ArticleReadingPage.tsx
- tobe_blog_web/src/portal/containers/home/GreatingSection.tsx
> Adjust basic layout

- tobe_blog_service/src/main/resources/com/tobe/blog/portal/mapper/PublicApiMapper.xml
- tobe_blog_web/src/global/types.ts
- tobe_blog_web/src/portal/PortalRoutes.tsx
- tobe_blog_web/src/portal/containers/personalPortal/IntroducationSection.tsx
- tobe_blog_web/src/portal/containers/personalPortal/PersonalPortalPage.tsx
- tobe_blog_web/src/services/PublicDataService.ts
> Add personal portal page

- tobe_blog_web/customization.json
- tobe_blog_web/src/admin/containers/content/components/GeneralCard.tsx
- tobe_blog_web/src/portal/containers/home/GreatingSection.tsx
- tobe_blog_web/src/portal/containers/personalPortal/IntroducationSection.tsx
> Add customization config json

- tobe_blog_web/src/admin/components/table/PagedTable.tsx
- tobe_blog_web/src/admin/components/table/TableButton.tsx
- tobe_blog_web/src/components/layout/HeaderUserMenu.tsx
- tobe_blog_web/src/portal/components/layout/PortalHeader.tsx
- tobe_blog_web/src/portal/components/layout/PortalLayout.tsx
- tobe_blog_web/src/portal/components/layout/SingleBoxLayout.tsx
> fix(sonar): fix the sonar error

- tobe_blog_service/pom.xml
- tobe_blog_web/env/.env.production
- tobe_blog_web/src/admin/components/navigator/SideNav.tsx
- tobe_blog_web/src/components/layout/Page.tsx
- tobe_blog_web/src/portal/components/ContentBanner.tsx
> Adjust UI for mobile orientation display

- tobe_blog_web/src/components/common/StrokeText.tsx
<div><img src="https://media4.giphy.com/media/MVDPX3gaKFPuo/giphy.gif?cid=5a38a5a2sanc6d4b5mlxbyzqrhhu91mwcgoyd4kojqbgatgb&amp;ep=v1_gifs_trending&amp;rid=giphy.gif&amp;ct=g" style="border:0;height:300px;width:300px"/></div>
> fix(tobe-icon): fix the display issue on safari and firefox

- tobe_blog_service/src/main/java/com/tobe/blog/content/job/ViewAndLikeCountSinkingJob.java
- tobe_blog_service/src/main/java/com/tobe/blog/core/utils/IpUtil.java
- tobe_blog_service/src/main/java/com/tobe/blog/portal/controller/PublicApiController.java
- tobe_blog_service/src/main/java/com/tobe/blog/portal/service/PublicApiService.java
- tobe_blog_web/public/locales/en/translation.json
- tobe_blog_web/public/locales/zh/translation.json
- tobe_blog_web/src/admin/containers/analytics/AnalyticsPage.tsx
- tobe_blog_web/src/commons/TimeFormat.ts
- tobe_blog_web/src/global/enums.ts
- tobe_blog_web/src/portal/components/ContentBanner.tsx
- tobe_blog_web/src/portal/components/ContentLikeButton.tsx
- tobe_blog_web/src/portal/components/ContentPageMetaBar.tsx
- tobe_blog_web/src/portal/containers/content/ContentReadingPage.tsx
- tobe_blog_web/src/portal/containers/home/FeaturedNews.tsx
- tobe_blog_web/src/portal/containers/home/NewsListItem.tsx
- tobe_blog_web/src/services/PublicDataService.ts
- Able to like content by click button
- Able to see like count of a specific content
> Add like content btn

- tobe_blog_service/src/main/java/com/tobe/blog/beans/dto/content/BaseSearchFilter.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/controller/IContentController.java
- tobe_blog_service/src/main/java/com/tobe/blog/content/controller/impl/BaseContentController.java
- tobe_blog_service/src/main/java/com/tobe/blog/core/utils/CacheUtil.java
- tobe_blog_service/src/main/resources/com/tobe/blog/content/mapper/BaseContentMapper.xml
- tobe_blog_web/src/admin/components/misc/selector/MultipleTagSelecter.tsx
- tobe_blog_web/src/admin/components/misc/selector/SingleTagSelecter.tsx
- tobe_blog_web/src/admin/containers/content/BaseContentService.ts
- tobe_blog_web/src/admin/containers/content/components/GeneralContentListPage.tsx
- tobe_blog_web/src/admin/containers/content/components/GeneralContentListPageFunctionBar.tsx
Add a tag filter in content list page in the back admin
> Add tag filter in content list page in admin

- tobe_blog_web/customization.json
- tobe_blog_web/src/portal/components/layout/PortalHeader.tsx
- tobe_blog_web/src/portal/components/layout/SingleBoxLayout.tsx
> Add github link

- tobe_blog_web/customization.json
- tobe_blog_web/env/.env
- tobe_blog_web/env/.env.development
- tobe_blog_web/env/.env.production
- tobe_blog_web/src/components/footer/CopyRight.tsx
> Refactering copyright component

- tobe_blog_web/src/admin/containers/content/plan/components/PlanProgressItems.tsx
> fixed compile issue

- tobe_blog_web/src/admin/components/misc/AddIconButton.tsx
- tobe_blog_web/src/admin/components/misc/CardHeaderActionButton.tsx
- tobe_blog_web/src/admin/components/navigator/SideNav.tsx
- tobe_blog_web/src/admin/containers/analytics/AnalyticsPage.tsx
- tobe_blog_web/src/admin/containers/content/components/ContentEditBar.tsx
- tobe_blog_web/src/admin/containers/content/components/GeneralCard.tsx
- tobe_blog_web/src/admin/containers/content/components/GeneralContentListPageFunctionBar.tsx
- tobe_blog_web/src/components/layout/Page.tsx
- tobe_blog_web/src/portal/containers/content/ContentReadingPage.tsx
- tobe_blog_web/src/portal/containers/home/FeaturedNews.tsx
- tobe_blog_web/src/portal/containers/home/NewsListItem.tsx
- tobe_blog_web/src/portal/containers/home/slider.css
> Optimize UI style

- tobe_blog_web/src/portal/components/RelevantContentsPanel.tsx
- tobe_blog_web/src/portal/components/RelvantContentIteam.tsx
- tobe_blog_web/src/portal/components/index.ts
- tobe_blog_web/src/portal/containers/content/ContentReadingPage.tsx
- tobe_blog_web/src/services/PublicDataService.ts
> Add relevant content panel

- tobe_blog_web/src/portal/components/ContentLikeButton.tsx
> fix-wrong-like-status-issue

- tobe_blog_web/src/commons/TimeFormat.ts
- tobe_blog_web/src/global/enums.ts
- tobe_blog_web/src/global/types.ts
> Remove useless codes

- tobe_blog_web/customization.json
- tobe_blog_web/public/locales/en/translation.json
- tobe_blog_web/public/locales/zh/translation.json
- tobe_blog_web/src/admin/containers/content/plan/components/PlanProgressItem.tsx
- tobe_blog_web/src/admin/containers/content/plan/components/PlanProgressItems.tsx
- tobe_blog_web/src/admin/containers/content/plan/components/PlanProgressModal.tsx
- tobe_blog_web/src/admin/containers/profileSettingPage/ProfileSettingPage.tsx
- tobe_blog_web/src/components/common/EditorStyle.ts
- tobe_blog_web/src/components/common/InfiniteScrollList.tsx
- tobe_blog_web/src/components/footer/CopyRight.tsx
- tobe_blog_web/src/portal/components/RelevantContentsPanel.tsx
- tobe_blog_web/src/portal/components/RelvantContentIteam.tsx
- tobe_blog_web/src/portal/containers/home/FeaturedNews.tsx
- tobe_blog_web/src/portal/containers/home/FunctionSection.tsx
- tobe_blog_web/src/portal/containers/home/GreatingSection.tsx
- tobe_blog_web/src/portal/containers/home/LoadingNewsSkeleton.tsx
- tobe_blog_web/src/portal/containers/home/NoContentNewsItem.tsx
- tobe_blog_web/src/portal/containers/home/TagFilterPanel.tsx
- tobe_blog_web/src/routes/URL.ts
- tobe_blog_web/src/services/PublicDataService.ts
- tobe_blog_web/vite.config.ts
> Feat/enhance UI

- tobe_blog_web/src/admin/components/misc/selector/MultipleTagSelecter.tsx
- tobe_blog_web/src/admin/components/misc/selector/SingleTagSelecter.tsx
- tobe_blog_web/src/admin/components/table/PagedTable.tsx
- tobe_blog_web/src/admin/containers/content/collection/CollectionDetailPage.tsx
- tobe_blog_web/src/admin/containers/content/components/GeneralCard.tsx
- tobe_blog_web/src/admin/containers/content/components/GeneralCardView.tsx
- tobe_blog_web/src/admin/containers/profileSettingPage/AvatarSelector.tsx
- tobe_blog_web/src/commons/TimeFormat.ts
- tobe_blog_web/src/commons/index.ts
- tobe_blog_web/src/components/common/word/WordDetailDialog.tsx
- tobe_blog_web/src/contexts/user/action.ts
- tobe_blog_web/src/portal/containers/content/ContentReadingPage.tsx
- tobe_blog_web/src/services/server.ts
> Fix sonar issues

- tobe_blog_service/README.md
- tobe_blog_service/doc/README_CH.md
- tobe_blog_service/pom.xml
- tobe_blog_service/src/main/java/com/tobe/blog/content/mapper/CollectionMapper.java
- tobe_blog_service/src/main/java/com/tobe/blog/portal/controller/PublicApiController.java
- tobe_blog_service/src/main/java/com/tobe/blog/portal/service/PublicApiService.java
> fix warnings

- tobe_blog_web/src/admin/components/misc/CardHeaderActionButton.tsx
- tobe_blog_web/src/admin/containers/content/article/draftStorage.ts
- tobe_blog_web/src/admin/containers/content/article/useAutoSaveDraft.ts
- tobe_blog_web/src/services/IndexedDBService.ts
> feat(idb): idb service improvement
